### PR TITLE
Version bump plugins

### PR DESCRIPTION
**Pull request by triplem**
Bumps (nearly) all plugins, except the openshift-pipeline plugin, which is copied directly. If wanted, I could add this as well.

### CODE REVIEW

**Comment by rawlingsj** [comment]
Thanks @triplem we're just trying to get a release out at the moment so wont merge this quite yet but will do once we're done.

BTW did you use a tool for this?

I created a little tool to work out the latest versions https://github.com/rawlingsj/jenkins-plugin-updater though its not battle tested it seems to work, do you have a similar approach?

**Comment by triplem** [comment]
Up until now, now tool for updating. Will take a look onto your tool, sounds interesting.

What do you think about the update of the openshift-pipeline? Could I move this into the plugins.txt as well, or do you like to stay with the static version? Just saw, that some of these static plugins do have a higher version number then the official ones at the jenkins page (kubernetes). This on purpose as well, I guess, right?

**Comment by rawlingsj** [comment]
Yeah the kubernetes one is locally built until fabric8 related PR are merged upstream https://github.com/jenkinsci/kubernetes-plugin/pulls

The openshift one can be added to the plugins.txt now though.  Think that was because it didn't exist in the jenkins update centre when we first added it.

**Comment by triplem** [comment]
Guess this is not needed anymore, if #89 is implemented.

**Comment by triplem** [comment]
This one will be closed, I will provide an updated version.

**Pull request closed without merging**
